def clear(port: int) -> None:
    ...
def distance(port: int) -> int:
    ...
def get_pixel(port: int, x: int, y: int) -> int:
    ...
def set_pixel(port: int, x: int, y: int, intensity: int) -> None:
    ...
def show(port: int, pixels: list[int]) -> None:
    ...

